
// This file has been generated by the GUI designer. Do not modify.
namespace Colours
{
	public partial class ColorGridWidget
	{
		private global::Gtk.Table table1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Colours.ColorGridWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Colours.ColorGridWidget";
			// Container child Colours.ColorGridWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(1)), ((uint)(1)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.Add(this.table1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
