
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action EditAction;
	
	private global::Gtk.Action ColorAction;
	
	private global::Gtk.Action undoAction;
	
	private global::Gtk.Action redoAction;
	
	private global::Gtk.VBox mainVbox;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.ComboBox schemeBox;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("_Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Edit");
		w1.Add (this.EditAction, null);
		this.ColorAction = new global::Gtk.Action ("ColorAction", global::Mono.Unix.Catalog.GetString ("_Color"), null, null);
		this.ColorAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Color");
		w1.Add (this.ColorAction, null);
		this.undoAction = new global::Gtk.Action ("undoAction", global::Mono.Unix.Catalog.GetString ("_Undo"), null, "gtk-undo");
		this.undoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Undo");
		w1.Add (this.undoAction, null);
		this.redoAction = new global::Gtk.Action ("redoAction", global::Mono.Unix.Catalog.GetString ("_Redo"), null, "gtk-redo");
		this.redoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Redo");
		w1.Add (this.redoAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mainVbox = new global::Gtk.VBox ();
		this.mainVbox.Name = "mainVbox";
		this.mainVbox.Spacing = 6;
		// Container child mainVbox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'EditAction\' action=\'EditAction\'><menuite" +
		"m name=\'undoAction\' action=\'undoAction\'/><menuitem name=\'redoAction\' action=\'red" +
		"oAction\'/></menu><menu name=\'ColorAction\' action=\'ColorAction\'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.mainVbox.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.mainVbox [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child mainVbox.Gtk.Box+BoxChild
		this.schemeBox = global::Gtk.ComboBox.NewText ();
		this.schemeBox.AppendText (global::Mono.Unix.Catalog.GetString ("Complement"));
		this.schemeBox.AppendText (global::Mono.Unix.Catalog.GetString ("Split Complements"));
		this.schemeBox.AppendText (global::Mono.Unix.Catalog.GetString ("Triads"));
		this.schemeBox.AppendText (global::Mono.Unix.Catalog.GetString ("Tetrads"));
		this.schemeBox.AppendText (global::Mono.Unix.Catalog.GetString ("Analogous"));
		this.schemeBox.AppendText (global::Mono.Unix.Catalog.GetString ("Monochromatic"));
		this.schemeBox.Name = "schemeBox";
		this.schemeBox.Active = 0;
		this.mainVbox.Add (this.schemeBox);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.mainVbox [this.schemeBox]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.Add (this.mainVbox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 644;
		this.DefaultHeight = 315;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.schemeBox.Changed += new global::System.EventHandler (this.OnSchemeBoxChanged);
	}
}
